//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.Shell.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public LocalizedMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAPICodePack.Shell.Resources.LocalizedMessages", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AddToMostRecentlyUsedList cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string AddToMostRecentlyUsedListCannotBeChanged {
            get {
                return ResourceManager.GetString("AddToMostRecentlyUsedListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlwaysAppendDefaultExtension cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string AlwaysAppendDefaultExtensionCannotBeChanged {
            get {
                return ResourceManager.GetString("AlwaysAppendDefaultExtensionCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index was outside the bounds of the CommonFileDialogComboBox. 的本地化字符串。
        /// </summary>
        public static string ComboBoxIndexOutsideBounds {
            get {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name not available - dialog was canceled. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogCanceled {
            get {
                return ResourceManager.GetString("CommonFileDialogCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell item could not be created. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogCannotCreateShellItem {
            get {
                return ResourceManager.GetString("CommonFileDialogCannotCreateShellItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle provided cannot be IntPtr.Zero. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogInvalidHandle {
            get {
                return ResourceManager.GetString("CommonFileDialogInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple files selected - the FileNames property should be used instead. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogMultipleFiles {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple files selected - the Items property should be used instead. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogMultipleItems {
            get {
                return ResourceManager.GetString("CommonFileDialogMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name not available - dialog has not closed yet. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogNotClosed {
            get {
                return ResourceManager.GetString("CommonFileDialogNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common File Dialog requires Windows Vista or later. 的本地化字符串。
        /// </summary>
        public static string CommonFileDialogRequiresVista {
            get {
                return ResourceManager.GetString("CommonFileDialogRequiresVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office Files 的本地化字符串。
        /// </summary>
        public static string CommonFiltersOffice {
            get {
                return ResourceManager.GetString("CommonFiltersOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Picture Files 的本地化字符串。
        /// </summary>
        public static string CommonFiltersPicture {
            get {
                return ResourceManager.GetString("CommonFiltersPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Files 的本地化字符串。
        /// </summary>
        public static string CommonFiltersText {
            get {
                return ResourceManager.GetString("CommonFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatePrompt cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string CreatePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("CreatePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom controls cannot be removed from a File dialog once added. 的本地化字符串。
        /// </summary>
        public static string DialogControlCollectionCannotRemoveControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control name cannot be null or zero length. 的本地化字符串。
        /// </summary>
        public static string DialogControlCollectionEmptyName {
            get {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommonFileDialogMenuItem controls can only be added to CommonFileDialogMenu controls. 的本地化字符串。
        /// </summary>
        public static string DialogControlCollectionMenuItemControlsCannotBeAdded {
            get {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifying controls collection while dialog is showing is not supported. 的本地化字符串。
        /// </summary>
        public static string DialogControlCollectionModifyingControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dialog cannot have more than one control with the same name. 的本地化字符串。
        /// </summary>
        public static string DialogControlCollectionMoreThanOneControl {
            get {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dialog control must be removed from current collections first. 的本地化字符串。
        /// </summary>
        public static string DialogControlCollectionRemoveControlFirst {
            get {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnsureFileExists cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string EnsureFileExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureFileExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnsurePathExists cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string EnsurePathExistsCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsurePathExistsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnsureReadOnly cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string EnsureReadonlyCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureReadonlyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EnsureValidNames cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string EnsureValidNamesCannotBeChanged {
            get {
                return ResourceManager.GetString("EnsureValidNamesCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browsing to object failed. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserBrowseToObjectFailed {
            get {
                return ResourceManager.GetString("ExplorerBrowserBrowseToObjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExplorerBrowser failed to get current view. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserFailedToGetView {
            get {
                return ResourceManager.GetString("ExplorerBrowserFailedToGetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get icon size. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserIconSize {
            get {
                return ResourceManager.GetString("ExplorerBrowserIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected error retrieving item count. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected error retrieving selected item count. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserSelectedItemCount {
            get {
                return ResourceManager.GetString("ExplorerBrowserSelectedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected error retrieving selection. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserUnexpectedError {
            get {
                return ResourceManager.GetString("ExplorerBrowserUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected error retrieving view items. 的本地化字符串。
        /// </summary>
        public static string ExplorerBrowserViewItems {
            get {
                return ResourceManager.GetString("ExplorerBrowserViewItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given path does not exist ({0}) 的本地化字符串。
        /// </summary>
        public static string FilePathNotExist {
            get {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guid does not identify a known folder. 的本地化字符串。
        /// </summary>
        public static string FolderIdsUnknownGuid {
            get {
                return ResourceManager.GetString("FolderIdsUnknownGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ControlPanel Category 的本地化字符串。
        /// </summary>
        public static string FolderTypeCategory {
            get {
                return ResourceManager.GetString("FolderTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ControlPanel Classic 的本地化字符串。
        /// </summary>
        public static string FolderTypeClassic {
            get {
                return ResourceManager.GetString("FolderTypeClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communications 的本地化字符串。
        /// </summary>
        public static string FolderTypeCommunications {
            get {
                return ResourceManager.GetString("FolderTypeCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressed Folder 的本地化字符串。
        /// </summary>
        public static string FolderTypeCompressedFolder {
            get {
                return ResourceManager.GetString("FolderTypeCompressedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contacts 的本地化字符串。
        /// </summary>
        public static string FolderTypeContacts {
            get {
                return ResourceManager.GetString("FolderTypeContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documents 的本地化字符串。
        /// </summary>
        public static string FolderTypeDocuments {
            get {
                return ResourceManager.GetString("FolderTypeDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Games 的本地化字符串。
        /// </summary>
        public static string FolderTypeGames {
            get {
                return ResourceManager.GetString("FolderTypeGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generic Library 的本地化字符串。
        /// </summary>
        public static string FolderTypeGenericLibrary {
            get {
                return ResourceManager.GetString("FolderTypeGenericLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid 的本地化字符串。
        /// </summary>
        public static string FolderTypeInvalid {
            get {
                return ResourceManager.GetString("FolderTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Library 的本地化字符串。
        /// </summary>
        public static string FolderTypeLibrary {
            get {
                return ResourceManager.GetString("FolderTypeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music 的本地化字符串。
        /// </summary>
        public static string FolderTypeMusic {
            get {
                return ResourceManager.GetString("FolderTypeMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music Icons 的本地化字符串。
        /// </summary>
        public static string FolderTypeMusicIcons {
            get {
                return ResourceManager.GetString("FolderTypeMusicIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Explorer 的本地化字符串。
        /// </summary>
        public static string FolderTypeNetworkExplorer {
            get {
                return ResourceManager.GetString("FolderTypeNetworkExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Specified 的本地化字符串。
        /// </summary>
        public static string FolderTypeNotSpecified {
            get {
                return ResourceManager.GetString("FolderTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Search 的本地化字符串。
        /// </summary>
        public static string FolderTypeOpenSearch {
            get {
                return ResourceManager.GetString("FolderTypeOpenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Users 的本地化字符串。
        /// </summary>
        public static string FolderTypeOtherUsers {
            get {
                return ResourceManager.GetString("FolderTypeOtherUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pictures 的本地化字符串。
        /// </summary>
        public static string FolderTypePictures {
            get {
                return ResourceManager.GetString("FolderTypePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printers 的本地化字符串。
        /// </summary>
        public static string FolderTypePrinters {
            get {
                return ResourceManager.GetString("FolderTypePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecordedTV 的本地化字符串。
        /// </summary>
        public static string FolderTypeRecordedTV {
            get {
                return ResourceManager.GetString("FolderTypeRecordedTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecycleBin 的本地化字符串。
        /// </summary>
        public static string FolderTypeRecycleBin {
            get {
                return ResourceManager.GetString("FolderTypeRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved Games 的本地化字符串。
        /// </summary>
        public static string FolderTypeSavedGames {
            get {
                return ResourceManager.GetString("FolderTypeSavedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Connector 的本地化字符串。
        /// </summary>
        public static string FolderTypeSearchConnector {
            get {
                return ResourceManager.GetString("FolderTypeSearchConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searches 的本地化字符串。
        /// </summary>
        public static string FolderTypeSearches {
            get {
                return ResourceManager.GetString("FolderTypeSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generic SearchResults 的本地化字符串。
        /// </summary>
        public static string FolderTypeSearchResults {
            get {
                return ResourceManager.GetString("FolderTypeSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Explorer 的本地化字符串。
        /// </summary>
        public static string FolderTypeSoftwareExplorer {
            get {
                return ResourceManager.GetString("FolderTypeSoftwareExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Files 的本地化字符串。
        /// </summary>
        public static string FolderTypeUserFiles {
            get {
                return ResourceManager.GetString("FolderTypeUserFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users Libraries 的本地化字符串。
        /// </summary>
        public static string FolderTypeUserLibraries {
            get {
                return ResourceManager.GetString("FolderTypeUserLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Videos 的本地化字符串。
        /// </summary>
        public static string FolderTypeVideos {
            get {
                return ResourceManager.GetString("FolderTypeVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsExpandedMode cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string IsExpandedModeCannotBeChanged {
            get {
                return ResourceManager.GetString("IsExpandedModeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom categories cannot be added while recent documents tracking is turned off. 的本地化字符串。
        /// </summary>
        public static string JumpListCustomCategoriesDisabled {
            get {
                return ResourceManager.GetString("JumpListCustomCategoriesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file type is not registered with this application. 的本地化字符串。
        /// </summary>
        public static string JumpListFileTypeNotRegistered {
            get {
                return ResourceManager.GetString("JumpListFileTypeNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JumpListLink&apos;s path is required and cannot be null. 的本地化字符串。
        /// </summary>
        public static string JumpListLinkPathRequired {
            get {
                return ResourceManager.GetString("JumpListLinkPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JumpListLink&apos;s title is required and cannot be null. 的本地化字符串。
        /// </summary>
        public static string JumpListLinkTitleRequired {
            get {
                return ResourceManager.GetString("JumpListLinkTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negative numbers are not allowed for the ordinal position. 的本地化字符串。
        /// </summary>
        public static string JumpListNegativeOrdinalPosition {
            get {
                return ResourceManager.GetString("JumpListNegativeOrdinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Given Known Folder ID is invalid. 的本地化字符串。
        /// </summary>
        public static string KnownFolderInvalidGuid {
            get {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing name is invalid. 的本地化字符串。
        /// </summary>
        public static string KnownFolderParsingName {
            get {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation of window has failed, view inner exception for details. 的本地化字符串。
        /// </summary>
        public static string MessageListenerCannotCreateWindow {
            get {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window class could not be registered, check inner exception for more details. 的本地化字符串。
        /// </summary>
        public static string MessageListenerClassNotRegistered {
            get {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message filter registration failed. 的本地化字符串。
        /// </summary>
        public static string MessageListenerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No listener handled of that value is registered. 的本地化字符串。
        /// </summary>
        public static string MessageListenerFilterUnknownListenerHandle {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create window on the listener thread because there is no existing window on the listener thread. 的本地化字符串。
        /// </summary>
        public static string MessageListenerNoWindowHandle {
            get {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NavigateToShortcut cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string NavigateToShortcutCannotBeChanged {
            get {
                return ResourceManager.GetString("NavigateToShortcutCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent cannot be null. 的本地化字符串。
        /// </summary>
        public static string NavigationLogNullParent {
            get {
                return ResourceManager.GetString("NavigationLogNullParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method or operation is not implemented. 的本地化字符串。
        /// </summary>
        public static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OverwritePrompt cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string OverwritePromptCannotBeChanged {
            get {
                return ResourceManager.GetString("OverwritePromptCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This CanonicalName is not a valid index. 的本地化字符串。
        /// </summary>
        public static string PropertyCollectionCanonicalInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This PropertyKey is not a valid index. 的本地化字符串。
        /// </summary>
        public static string PropertyCollectionInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument CanonicalName cannot be null or empty. 的本地化字符串。
        /// </summary>
        public static string PropertyCollectionNullCanonicalName {
            get {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index was outside the bounds of the CommonFileDialogRadioButtonList. 的本地化字符串。
        /// </summary>
        public static string RadioButtonListIndexOutOfBounds {
            get {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RestoreDirectory cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string RestoreDirectoryCannotBeChanged {
            get {
                return ResourceManager.GetString("RestoreDirectoryCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieved a null shell item from dialog. 的本地化字符串。
        /// </summary>
        public static string SaveFileNullItem {
            get {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Given property key is invalid. 的本地化字符串。
        /// </summary>
        public static string SearchConditionFactoryInvalidProperty {
            get {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell Exception has occurred, look at inner exception for information. 的本地化字符串。
        /// </summary>
        public static string ShellExceptionDefaultText {
            get {
                return ResourceManager.GetString("ShellExceptionDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetParsingName has failed. 的本地化字符串。
        /// </summary>
        public static string ShellHelperGetParsingNameFailed {
            get {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given CanonicalName is not valid. 的本地化字符串。
        /// </summary>
        public static string ShellInvalidCanonicalName {
            get {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DefaultSaveFolder path not found. 的本地化字符串。
        /// </summary>
        public static string ShellLibraryDefaultSaveFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LibraryName cannot be empty. 的本地化字符串。
        /// </summary>
        public static string ShellLibraryEmptyName {
            get {
                return ResourceManager.GetString("ShellLibraryEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder path not found. 的本地化字符串。
        /// </summary>
        public static string ShellLibraryFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid FolderType Guid. 的本地化字符串。
        /// </summary>
        public static string ShellLibraryInvalidFolderType {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given known folder is not a valid library. 的本地化字符串。
        /// </summary>
        public static string ShellLibraryInvalidLibrary {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t get the display name. 的本地化字符串。
        /// </summary>
        public static string ShellObjectCannotGetDisplayName {
            get {
                return ResourceManager.GetString("ShellObjectCannotGetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination array too small, or invalid arrayIndex. 的本地化字符串。
        /// </summary>
        public static string ShellObjectCollectionArrayTooSmall {
            get {
                return ResourceManager.GetString("ShellObjectCollectionArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must have at least one shell object in the collection. 的本地化字符串。
        /// </summary>
        public static string ShellObjectCollectionEmptyCollection {
            get {
                return ResourceManager.GetString("ShellObjectCollectionEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot insert items into a read only list. 的本地化字符串。
        /// </summary>
        public static string ShellObjectCollectionInsertReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionInsertReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot remove items from a read only list. 的本地化字符串。
        /// </summary>
        public static string ShellObjectCollectionRemoveReadOnly {
            get {
                return ResourceManager.GetString("ShellObjectCollectionRemoveReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell item could not be created. 的本地化字符串。
        /// </summary>
        public static string ShellObjectCreationFailed {
            get {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell Object creation requires Windows Vista or higher operating system. 的本地化字符串。
        /// </summary>
        public static string ShellObjectFactoryPlatformNotSupported {
            get {
                return ResourceManager.GetString("ShellObjectFactoryPlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to Create Shell Item. 的本地化字符串。
        /// </summary>
        public static string ShellObjectFactoryUnableToCreateItem {
            get {
                return ResourceManager.GetString("ShellObjectFactoryUnableToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration for change notification has failed. 的本地化字符串。
        /// </summary>
        public static string ShellObjectWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to change watched events while listening. 的本地化字符串。
        /// </summary>
        public static string ShellObjectWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value on this property cannot be set. To set the property value, use the ShellObject that is associated with this property. 的本地化字符串。
        /// </summary>
        public static string ShellPropertyCannotSetProperty {
            get {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No constructor found matching requested argument types. 的本地化字符串。
        /// </summary>
        public static string ShellPropertyFactoryConstructorNotFound {
            get {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to set property. 的本地化字符串。
        /// </summary>
        public static string ShellPropertySetValue {
            get {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get writable property store for this property. 的本地化字符串。
        /// </summary>
        public static string ShellPropertyUnableToGetWritableProperty {
            get {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value had to be truncated in a string or rounded if a numeric value. Set AllowTruncatedValue to true to prevent this exception. 的本地化字符串。
        /// </summary>
        public static string ShellPropertyValueTruncated {
            get {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Property is available on Windows 7 only. 的本地化字符串。
        /// </summary>
        public static string ShellPropertyWindows7 {
            get {
                return ResourceManager.GetString("ShellPropertyWindows7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property only accepts a value of type \&quot;{0}\&quot;. 的本地化字符串。
        /// </summary>
        public static string ShellPropertyWrongType {
            get {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to set list of sort columns. 的本地化字符串。
        /// </summary>
        public static string ShellSearchFolderUnableToSetSortColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to set visible columns. 的本地化字符串。
        /// </summary>
        public static string ShellSearchFolderUnableToSetVisibleColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentSize (width or height) cannot be greater than the maximum size: {0}. 的本地化字符串。
        /// </summary>
        public static string ShellThumbnailCurrentSizeRange {
            get {
                return ResourceManager.GetString("ShellThumbnailCurrentSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current ShellObject does not have a thumbnail. Try using ShellThumbnailFormatOption.Default to get the icon for this item. 的本地化字符串。
        /// </summary>
        public static string ShellThumbnailDoesNotHaveThumbnail {
            get {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current ShellObject does not have a valid thumbnail handler or there was a problem in extracting the thumbnail for this specific shell object. 的本地化字符串。
        /// </summary>
        public static string ShellThumbnailNoHandler {
            get {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentSize (width or height) cannot be 0. 的本地化字符串。
        /// </summary>
        public static string ShellThumbnailSizeCannotBe0 {
            get {
                return ResourceManager.GetString("ShellThumbnailSizeCannotBe0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowHiddenItems cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string ShowHiddenItemsCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowHiddenItemsCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show places list cannot be changed while dialog is showing. 的本地化字符串。
        /// </summary>
        public static string ShowPlacesListCannotBeChanged {
            get {
                return ResourceManager.GetString("ShowPlacesListCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Stock Icon identifier given is invalid ({0}). 的本地化字符串。
        /// </summary>
        public static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child control&apos;s window handle cannot be zero. 的本地化字符串。
        /// </summary>
        public static string TabbedThumbnailZeroChildHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroChildHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent window handle cannot be zero. 的本地化字符串。
        /// </summary>
        public static string TabbedThumbnailZeroParentHandle {
            get {
                return ResourceManager.GetString("TabbedThumbnailZeroParentHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabbedThumbnailProxyWindow has not been set. 的本地化字符串。
        /// </summary>
        public static string TasbarWindowProxyWindowSet {
            get {
                return ResourceManager.GetString("TasbarWindowProxyWindowSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A valid active Window is needed to update the Taskbar. 的本地化字符串。
        /// </summary>
        public static string TaskbarManagerValidWindowRequired {
            get {
                return ResourceManager.GetString("TaskbarManagerValidWindowRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array of buttons must contain at least 1 item. 的本地化字符串。
        /// </summary>
        public static string TaskbarWindowEmptyButtonArray {
            get {
                return ResourceManager.GetString("TaskbarWindowEmptyButtonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool bar buttons for this window are already added. Please refer to the Remarks section of the AddButtons method for more information on updating the properties or hiding existing buttons. 的本地化字符串。
        /// </summary>
        public static string TaskbarWindowManagerButtonsAlreadyAdded {
            get {
                return ResourceManager.GetString("TaskbarWindowManagerButtonsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is already set. It cannot be set more than once. 的本地化字符串。
        /// </summary>
        public static string TaskbarWindowValueSet {
            get {
                return ResourceManager.GetString("TaskbarWindowValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given control has not been added to the taskbar. 的本地化字符串。
        /// </summary>
        public static string ThumbnailManagerControlNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerControlNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window handle is invalid. 的本地化字符串。
        /// </summary>
        public static string ThumbnailManagerInvalidHandle {
            get {
                return ResourceManager.GetString("ThumbnailManagerInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This preview has already been added. 的本地化字符串。
        /// </summary>
        public static string ThumbnailManagerPreviewAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given preview has not been added to the taskbar. 的本地化字符串。
        /// </summary>
        public static string ThumbnailManagerPreviewNotAdded {
            get {
                return ResourceManager.GetString("ThumbnailManagerPreviewNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of buttons allowed is 7. 的本地化字符串。
        /// </summary>
        public static string ThumbnailToolbarManagerMaxButtons {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerMaxButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null or empty arrays are not allowed. 的本地化字符串。
        /// </summary>
        public static string ThumbnailToolbarManagerNullEmptyArray {
            get {
                return ResourceManager.GetString("ThumbnailToolbarManagerNullEmptyArray", resourceCulture);
            }
        }
    }
}
